### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by jaap3** [trapeze/fancy_tag#3]
I've just noticed you've registered your package @ pypi.python.org (http://pypi.python.org/pypi/fancy_tag/0.1.4). Any chance you also want to upload it there as well?

```
python setup.py sdist upload
```

I'm currently using github's zipball as a find-link, works just fine but having it on pypi is even easier ;-)

```
https://github.com/trapeze/fancy_tag/zipball/0.1.4#egg=fancy-tag-0.1.4
```

**Comment by greatestape** [comment]
I'm totally new to submitting things to pypi. I didn't know you had to upload the download resources separately. It's done now.

Thanks again for your help!

**Comment by greatestape** [comment]
ah. It's done /now/. I had to alter the setup.py so that the text files would be included. I also fixed formatting in the readme. I tagged it 0.1.5.

**Comment by jaap3** [comment]
Thank you! fancy_tag is very useful to me, probably is to many others. Having it available on PyPi is a good thing for everyone.

I recently came across http://djangopackages.com/ you could register it on there as well. I imagine there are more people fed up with having to write complicated code for a just a template tag.
